/** @type {import('tailwindcss').Config} */

const spacing = {
  xxs: 4,
  xs: 8,
  s: 12,
  m: 16,
  l: 24,
  xl: 32,
  xxl: 64,
}

module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    borderRadius: {
      xs: 3,
      s: 6,
      m: 10,
      l: 16,
      xl: 24,
      full: 9999,
    },
    colors: {
      transparent: 'transparent',
      warning: '#FF923B',
      success: '#228C59',
      danger: '#AE3232',
      disabled: '#E1DCDC',
      white: {
        strong: '#C0C0C0',
        classic: '#FFFCF9',
        electric: '#F2F2F2',
        pale: '#F0F0F0',
        light: '#FFFFFF',
      },
      black: {
        strong: '#000000',
        classic: '#171A20',
        electric: '#222222',
        pale: '#333333',
        light: '#444444',
      },
      grey: {
        strong: '#505050',
        classic: '#808080',
        electric: '#708090',
        pale: '#C0C0C0',
        light: '#D3D3D3',
      },
      primary: {
        strong: '#FFA500',
        classic: '#FFB300',
        electric: '#FFD700',
        pale: '#FFFF99',
        light: '#FFFACD',
      },
      secondary: {
        strong: '#4B0082',
        classic: '#BB99DD',
        electric: '#8A2BE2',
        pale: '#D8BFD8',
        light: '#E6E6FA',
      },
      ternary: {
        strong: '#082567',
        classic: '#5A93D3',
        electric: '#0074E4',
        pale: '#ADD8E6',
        light: '#E6F7FF',
      },
      orange: {
        strong: '#FFA500',
        classic: '#FF8C00',
        electric: '#FFD700',
        pale: '#FFECB3',
        light: '#FFF9E6',
      },
      blue: {
        strong: '#1E90FF',
        classic: '#000080',
        electric: '#4682B4',
        pale: '#B0C4DE',
        light: '#BFEFFF',
      },
      green: {
        strong: '#006400',
        classic: '#228B22',
        electric: '#7CFC00',
        pale: '#98FB98',
        light: '#E5FFE5',
      },
      red: {
        strong: '#8B0000',
        classic: '#DC143C',
        electric: '#FF0000',
        pale: '#FFB6C1',
        light: '#FFDAB9',
      },
      yellow: {
        strong: '#FFD700',
        classic: '#FFC125',
        electric: '#FFDA6A',
        pale: '#FFFACD',
        light: '#FFFFCC',
      },
      purple: {
        strong: '#8A2BE2',
        classic: '#4B0082',
        electric: '#800080',
        pale: '#9370DB',
        light: '#D8BFD8',
      },
      pink: {
        strong: '#FF0066',
        classic: '#FF6EB4',
        electric: '#FF1493',
        pale: '#FFC0CB',
        light: '#FFEBF3',
      },
      brown: {
        strong: '#8B4513',
        classic: '#A52A2A',
        electric: '#CD853F',
        pale: '#D2691E',
        light: '#D2B48C',
      },
    },
    spacing,
    screens: {
      sm: '390px',
      md: '700px',
      lg: '624px',
      xl: '1080px',
      '2xl': '1536px',
    },
    height: {
      calendar: 250,
      ...spacing,
    },
  },
  plugins: [],
}
