# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Builds or Update with EAS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build or update'
        required: true
        default: 'warning'
        type: choice
        options:
          - dev
          - staging
          - production
      platform:
        description: 'Select your target'
        required: true
        default: 'warning'
        type: choice
        options:
          - android
          - ios
          - all
      command:
        description: 'Build or Update'
        required: true
        default: 'warning'
        type: choice
        options:
          - build
          - update
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
      EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
      NODE_OPTIONS: '--max-old-space-size=12288'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 📦 Install dependencies
        run: yarn install

      - name: 📦 EAS
        run: APP_ENV=${{github.event.inputs.environment}} npx eas-cli ${{ github.event.inputs.command }} --profile ${{ github.event.inputs.environment }} --non-interactive --platform ${{ github.event.inputs.platform }}
